# lab-1-ot-security/kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080 # Port Web UI OpenPLC
    hostPort: 30080
    protocol: TCP
  - containerPort: 30502 # Port Modbus OpenPLC
    hostPort: 30502
    protocol: TCP